### ISSUE TITLE
Your code is very incomplete

### ISSUE THREAD

**Issue by gghhoosstt** [Nardien/NMG#3]
Your code is very incomplete，the imdb and chemprot are not implemented, there are other errors. Could you please upload the complete code？

**Comment by Nardien** [comment]
Thank you for pointing out the issues. As you mentioned and as written in README.md, we only uploaded the question answering version of the code. We will upload the text classification version as soon as possible. (It means that the current version of glue_worker.py may not work.)

Due to the huge updates on the huggingface transformers library, it may not work well with the current version of the libraries. If you find any errors in this code, please let us know in detail. Thank you.

**Comment by gghhoosstt** [comment]
ok, thank you.
